export const state = {
  route: "plots",
  plots: [],
  chars: new Map(),
  users: new Map(),
  catalogPages: {
    plots: { nextCursor: null, hasMore: false, loading: false },
    chars: { nextCursor: null, hasMore: false, loading: false },
    users: { nextCursor: null, hasMore: false, loading: false },
  },
  selectedPlot: null,
  selectedUserProfileId: null,
  managedPlotId: null,
  conversation: null,
  conversations: [],
  conversationPage: { nextCursor: null, hasMore: false, loading: false },
  hasMore: false,
  nextCursor: null,
  streaming: false,
  composerEdit: null,
  pendingUserResend: null,
  composerHeight: null,
  composerMaxHeight: 136,
  settings: {
    provider: "local-stub",
    model: "local-stub",
    numPredict: 1500,
    numCtx: 8192,
    compactPrompt: true,
    adapterId: "",
  },
};
